baseURL = "https://blog.trr.co.kr/"
title = "트라움자원 필드노트"
languageCode = "ko-kr"
enableRobotsTXT = true

# Hugo v0.128.0+ pagination config
[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = false
    style = "dracula"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
description = "트라움자원 현장·시장·운영의 기록"
kakao_js_key = "" # 배포 환경에서는 HUGO_PARAMS_KAKAO_JS_KEY 로 주입 권장
kakao_image_fallback = "" # 선택: 카카오 공유용 기본 이미지(절대 URL 권장)
