services:
  blog:
    build:
      context: .
      args:
        HUGO_ENV: development
    image: traum/blog:local
    container_name: traum-blog
    ports:
      - "127.0.0.1:17177:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "test", "-f", "/usr/share/nginx/html/index.html"]
      interval: 10s
      timeout: 3s
      retries: 5

  # GitHub OAuth provider for Decap CMS
  oauth:
    build: ./oauth
    image: traum/blog-oauth:local
    container_name: traum-blog-oauth
    env_file:
      - ./.env
    environment:
      - PORT=3000
    ports:
      - "127.0.0.1:17178:3000"
    restart: unless-stopped
