extends: ['@commitlint/config-conventional']
rules:
  subject-case:
    - 0
    - never
    - []
  subject-full-stop:
    - 2
    - never
  header-max-length:
    - 2
    - always
    - 72
  type-enum:
    - 2
    - always
    - [feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert, content, post, blog]
