backend:
  name: github
  repo: ginishuh/traum_homepage
  branch: main
  base_url: http://localhost:17177
  auth_endpoint: oauth/auth
  site_domain: localhost:17177

publish_mode: editorial_workflow
media_folder: "traum_blog/static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "traum_blog/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
