baseURL = "http://localhost:17177/"
title = "트라움자원 필드노트"
languageCode = "ko-kr"
enableRobotsTXT = true

# Hugo v0.128.0+ pagination config
[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "RSS"]

[params]
description = "트라움자원 현장·시장·운영의 기록"
