name: Commitlint (PR only)

on:
  pull_request:
    branches: [ main ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
