name: Deploy Web (compose build + up)

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'nginx.conf'
      - 'docker-compose.yml'
      - '.github/workflows/deploy-web.yml'
  workflow_dispatch:

concurrency:
  group: deploy-web
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_SSH_PORT: ${{ secrets.DEPLOY_SSH_PORT }}
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check required secrets
        run: |
          set -euo pipefail
          missing=0
          for var in DEPLOY_HOST DEPLOY_USER DEPLOY_SSH_KEY; do
            if [ -z "${!var:-}" ]; then
              echo "::error title=Missing secret::${var} is not set in repository Actions secrets";
              missing=$((missing+1))
            fi
          done
          if [ -z "${DEPLOY_SSH_PORT:-}" ]; then
            echo "info: DEPLOY_SSH_PORT not set, defaulting to 22";
          fi
          if [ $missing -gt 0 ]; then
            echo "Some required secrets are missing. Add them in Settings → Secrets and variables → Actions.";
            exit 1;
          fi

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Verify SSH key loaded (debug)
        run: |
          set -e
          echo "ssh-add identities:"; ssh-add -l -E md5 || ssh-add -l || true
          echo "ssh version:"; ssh -V

      - name: Test SSH connectivity (debug)
        run: |
          set -e
          : "${DEPLOY_SSH_PORT:=22}"
          echo "Testing SSH to $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_SSH_PORT"
          ssh -o BatchMode=yes -o StrictHostKeyChecking=no -p "$DEPLOY_SSH_PORT" -v "$DEPLOY_USER@$DEPLOY_HOST" 'echo OK from $(hostname)'

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          : "${DEPLOY_SSH_PORT:=22}"
          ssh-keyscan -p "$DEPLOY_SSH_PORT" -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts

      - name: Deploy web via SSH
        run: |
          : "${DEPLOY_SSH_PORT:=22}"
          REPO_URL="${{ github.server_url }}/${{ github.repository }}.git"
          ssh -p "$DEPLOY_SSH_PORT" "$DEPLOY_USER@$DEPLOY_HOST" \
            "bash -se -c 'set -euo pipefail; \
            mkdir -p /srv/traum_homepage; \
            cd /srv/traum_homepage; \
            if [ -d .git ]; then git fetch --prune origin main && git reset --hard origin/main; \
            else echo Cloning repository\ \(first\ deploy\)…; git clone --depth=1 \"$REPO_URL\" .; fi; \
            if docker compose version >/dev/null 2>&1; then DOCKER_COMPOSE=\"docker compose\"; \
            elif docker-compose version >/dev/null 2>&1; then DOCKER_COMPOSE=\"docker-compose\"; \
            else echo docker\ compose\ not\ found >&2; exit 1; fi; \
            $DOCKER_COMPOSE build web; \
            $DOCKER_COMPOSE up -d web; \
            sleep 2; \
            curl -sI http://127.0.0.1:17176 | sed -n \"1,5p\" || true; \
            docker ps --format \"table {{.Names}}\t{{.Image}}\t{{.Status}}\" | sed -n \"1,20p\"'"

      # Slack 알림 스텝 제거됨 (미사용)
