name: Deploy Blog (Hugo ➜ rsync)

on:
  push:
    branches: [ main ]
    paths:
      - 'traum_blog/**'
  workflow_dispatch:

concurrency:
  group: deploy-blog
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_SSH_PORT: ${{ secrets.DEPLOY_SSH_PORT }}
      DEST: /srv/traum_homepage/traum_blog/public/
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check required secrets
        run: |
          set -euo pipefail
          missing=0
          for var in DEPLOY_HOST DEPLOY_USER DEPLOY_SSH_KEY; do
            if [ -z "${!var:-}" ]; then
              echo "::error title=Missing secret::${var} is not set in repository Actions secrets";
              missing=$((missing+1))
            fi
          done
          if [ -z "${DEPLOY_SSH_PORT:-}" ]; then
            echo "info: DEPLOY_SSH_PORT not set, defaulting to 22";
          fi
          if [ $missing -gt 0 ]; then
            echo "Some required secrets are missing. Add them in Settings → Secrets and variables → Actions.";
            exit 1;
          fi

      - name: Setup Hugo (extended)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build blog with Hugo
        working-directory: traum_blog
        run: |
          set -euo pipefail
          hugo --minify
          echo "\nBuilt files:" && find public -maxdepth 2 -type f | sed -n '1,50p'

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          : "${DEPLOY_SSH_PORT:=22}"
          ssh-keyscan -p "$DEPLOY_SSH_PORT" -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts

      - name: Rsync public/ to VPS
        run: |
          : "${DEPLOY_SSH_PORT:=22}"
          rsync -az --delete \
            --rsync-path="mkdir -p '$DEST' && rsync" \
            -e "ssh -p $DEPLOY_SSH_PORT -o StrictHostKeyChecking=no" \
            traum_blog/public/ "$DEPLOY_USER@$DEPLOY_HOST:$DEST"


      # Slack 알림 스텝 제거됨 (미사용)
